### ISSUE TITLE
Workspace Invocation

### ISSUE THREAD

**Issue by seanpianka** [lava-xyz/rust-ontologist#2]
I have a project that is an existing workspace of unpublished, private crates containing both library and binary crates. How do I use this project to visualize it?

**Comment by Hirrolot** [comment]
`rust-ontologist` is able to handle workspaces just like any other Cargo projects. Have you encountered an error while trying to do so?

**Comment by seanpianka** [comment]
> `rust-ontologist` is able to handle workspaces just like any other Cargo projects. Have you encountered an error while trying to do so?

I might be dense, but I don't entirely understand how to set this up such that I can run it in an existing workspace project. Do I `cargo install` the binary and then run it from my project, specifying some entrypoint/binary crate as the argument to `-p`?

**Comment by Hirrolot** [comment]
You can install the binary as well, but it's not required. Simply specify your workspace via `-p` (as in the README), and you should be good.

**Comment by seanpianka** [comment]
Got it. I didn't realize I could specify `.` as the argument to `-p`. The following worked:
```
$ cd workspace-project
$ ../rust-ontologist/target/release/rust-ontologist -p . --enable-edges
$ mv codebase-dump.json ../rust-ontologist
$ # remaining steps from README
```
